version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /tictactoe
        volumes:
            - './application:/tictactoe'
        environment:
            - MYSQL_ROOT_PASSWORD=tictactoe
            - MYSQL_DATABASE=tictactoe
            - MYSQL_USER=tictactoe
            - MYSQL_PASSWORD=tictactoe
        ports:
            - '17002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /tictactoe
        volumes:
            - './application:/tictactoe'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '17000:80'

    php-fpm:
        build: .docker/php-fpm
        working_dir: /tictactoe
        volumes:
            - './application:/tictactoe'
            - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
